name: CLI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          set -ex
          sudo apt install make -y
          make build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Linux AMD64 Asset
        id: upload-release-asset-linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/k8s-watch-linux-amd64
          asset_name: k8s-watch-linux-amd64
          asset_content_type: multipart/form-data
      - name: Upload Linux ARM64 Asset
        id: upload-release-asset-linux-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/k8s-watch-linux-arm64
          asset_name: k8s-watch-linux-arm64
          asset_content_type: multipart/form-data
      - name: Upload Darwin AMD64 Asset
        id: upload-release-asset-darwin-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/k8s-watch-darwin-amd64
          asset_name: k8s-watch-darwin-amd64
          asset_content_type: multipart/form-data
      - name: Upload Darwin ARM64 Asset
        id: upload-release-asset-darwin-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/k8s-watch-darwin-arm64
          asset_name: k8s-watch-darwin-arm64
          asset_content_type: multipart/form-data
      - name: Upload Windows AMD64 Asset
        id: upload-release-asset-windows-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/k8s-watch-windows-amd64.exe
          asset_name: k8s-watch-windows-amd64.exe
          asset_content_type: multipart/form-data
      - name: Upload Windows Arm64 Asset
        id: upload-release-asset-windows-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/k8s-watch-windows-arm64.exe
          asset_name: k8s-watch-windows-arm64.exe
          asset_content_type: multipart/form-data