name: Docker Image CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.REGISTERY_USERNAME }}
          password: ${{ secrets.REGISTERY_PASSWORD }}
      - name: Build the Docker image
        run: |
          docker buildx create --use --platform=linux/amd64,linux/arm64,linux/ppc64le --name multi-platform-builder
          docker buildx ls
          IMG=registry.cn-hangzhou.aliyuncs.com/ls-2018/k8s-watch-server:${{ github.ref_name }} make docker-multiarch
          IMG=registry.cn-hangzhou.aliyuncs.com/ls-2018/k8s-watch-server:latest make docker-multiarch